export const OPEN_TO_BUDGETS_SOLICITATION_STATUS = "ABERTO PARA ORÇAMENTOS"
export const DIRECT_SOLICITATION = "SOLICITAÇÃO DIRETA"
export const ACCEPTED_BUDGET_SOLICITATION_STATUS = "ORÇAMENTO ACEITO"
export const CANCELED_SOLICITATION_STATUS = "ORÇAMENTO CANCELADO"
